"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { Footer, Header, Reveal } from "./components/SiteChrome";

export default function Home(){
 const [mode,setMode]=useState<"upload"|"ai">("upload"); const [file,setFile]=useState(""); const input=useRef<HTMLInputElement>(null);
 return <main><Header/>
  <section className="saas-hero"><div className="hero-glow"/><Reveal className="hero-copy"><span className="pill"><i/> Web tabanlı 3D + AR platformu</span><h1>3D içeriğiniz için<br/><span>tek çalışma alanı.</span></h1><p>Modelleri yükleyin, optimize edin, AI ile üretin ve web ile artırılmış gerçeklikte yayınlayın. Ekipler için tasarlanmış modern 3D operasyon platformu.</p><div className="hero-actions"><a className="primary-btn" href="#start">Ücretsiz başlayın <span>→</span></a><Link className="secondary-btn" href="/workflow">Nasıl çalışır <span>↗</span></Link></div><div className="trust-row"><span>✓ Kredi kartı gerekmez</span><span>✓ 5 dakikada kurulum</span><span>✓ İstediğiniz zaman iptal</span></div></Reveal>
   <Reveal className="product-shell" delay={150}><div className="window-bar"><span className="window-dots">● ● ●</span><span>workspace.arvision.app</span><span>⌘ K</span></div><div className="app-ui"><aside><b>A</b>{["⌂","◇","◫","⌁","⚙"].map((x,i)=><span className={i===1?"active":""} key={x}>{x}</span>)}</aside><div className="dashboard"><div className="dash-head"><div><small>WORKSPACE / MODELLER</small><h3>Model Kitaplığı</h3></div><button>+ Yeni model</button></div><div className="stats"><article><span>TOPLAM MODEL</span><b>248</b><em>+12 bu ay</em></article><article><span>GÖRÜNTÜLEME</span><b>84.2K</b><em>↗ %18.4</em></article><article><span>DEPOLAMA</span><b>6.8 GB</b><em>10 GB’ın %68’i</em></article></div><div className="model-grid">{["Chair / V4","Sneaker / Final","Lamp / V2"].map((x,i)=><article key={x}><div className={`model-shape shape-${i}`}><span>360°</span></div><b>{x}</b><small>GLB · optimize</small></article>)}</div></div></div></Reveal>
  </section>
  <section className="logo-cloud"><span>Üretimden yayına açık standartlarla</span><b>GLB + USDZ</b><b>iOS Quick Look</b><b>Android Scene Viewer</b><b>Shopify</b><b>REST API</b></section>
  <section className="home-section" id="start"><Reveal><span className="section-tag">01 — BAŞLAYIN</span><h2>Dosyadan canlı deneyime.<br/><span>Tek bir akışta.</span></h2></Reveal><div className="upload-layout"><Reveal className="upload-card"><div className="mode-tabs"><button className={mode==="upload"?"selected":""} onClick={()=>setMode("upload")}>Dosya yükle</button><button className={mode==="ai"?"selected":""} onClick={()=>setMode("ai")}>AI ile üret <em>PRO</em></button></div>{mode==="upload"?<><input hidden ref={input} type="file" onChange={e=>setFile(e.target.files?.[0]?.name||"")}/><button className="dropzone" onClick={()=>input.current?.click()}><span>↑</span><b>{file||"3D modelinizi buraya bırakın"}</b><small>STL, OBJ, FBX, STEP veya ZIP · Maks. 100 MB</small></button><button className="primary-btn wide" disabled={!file}>{file?"Dönüştürmeyi başlat →":"Bir dosya seçin"}</button></>:<><textarea className="prompt-box" placeholder="Örn. Mat siyah, modüler bir masa lambası..."/><button className="primary-btn wide">Modeli üret →</button></>}</Reveal><div className="mini-features">{[["01","Otomatik optimizasyon","Meshopt ve Draco ile daha hızlı yüklenen modeller."],["02","Her cihazda AR","iOS Quick Look ve Android Scene Viewer hazır."],["03","Anında paylaşım","Link, QR, embed ve e-ticaret entegrasyonları."]].map((x,i)=><Reveal key={x[0]} delay={i*90}><article><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div><b>↗</b></article></Reveal>)}</div></div></section>
  <section className="ar-showcase"><div className="ar-showcase-copy"><Reveal><span className="section-tag">02 — GERÇEK DÜNYADA</span><h2>Aynı model.<br/><span>Üç gerçeklik.</span></h2><p>Kaynak geometriden optimize edilmiş web modeline, oradan gerçek ölçekte AR yerleşimine geçin. Aynı varlık; aynı materyal, ölçek ve ürün kimliğiyle her ekranda tutarlı kalır.</p><div className="showcase-points"><span><b>01</b> Geometri ve materyal önizlemesi</span><span><b>02</b> Web’de gerçek zamanlı görüntüleme</span><span><b>03</b> iOS ve Android’de AR yerleşimi</span></div><Link href="/studio" className="primary-btn">Studio’da deneyin <span>→</span></Link></Reveal></div><Reveal className="ar-visual" delay={120}><img src="/ar-studio-scene.png" alt="Bir masa lambasının tel kafes 3D modelden fiziksel ürüne ve telefonda artırılmış gerçeklik görünümüne geçişi"/><div className="ar-float ar-float-top"><i/> AR ÇIKTISI HAZIR</div><div className="ar-float ar-float-bottom"><b>1:1</b><span>TUTARLI ÖLÇEK</span></div></Reveal></section>
  <section className="metrics capability-strip"><Reveal><strong>GLB + USDZ</strong><span>web ve mobil AR çıktısı</span></Reveal><Reveal delay={100}><strong>iOS + Android</strong><span>uygulamasız AR açılışı</span></Reveal><Reveal delay={200}><strong>Link + Embed</strong><span>kontrollü model paylaşımı</span></Reveal><Reveal delay={300}><strong>API + Webhook</strong><span>otomasyon ve entegrasyon</span></Reveal></section>
  <section className="cta-band"><Reveal><span className="pill light">ARVision ile tanışın</span><h2>3D operasyonunuzu<br/>bugün modernleştirin.</h2><p>İlk modelinizi ücretsiz yayınlayın. Kurulum veya kredi kartı gerekmez.</p><a href="#start" className="light-btn">Ücretsiz başlayın →</a></Reveal></section><Footer/></main>
}
