"use client";
import {Footer,Header,PageHero,Reveal} from "../components/SiteChrome";
const plans=[{name:"Free",price:"$0",copy:"İlk modellerini yayınlayanlar için.",features:["1 GB depolama","10 model","50 MB yükleme","7 günlük analitik"]},{name:"Pro",price:"$19",copy:"Bağımsız üreticiler ve profesyoneller için.",popular:true,features:["10 GB depolama","200 model","20 AI üretimi / ay","API erişimi","Şifreli paylaşım","90 günlük analitik"]},{name:"Business",price:"$99",copy:"Ekipler ve yüksek hacimli işler için.",features:["100 GB depolama","Sınırsız model","200 AI üretimi / ay","Organizasyon rolleri","Özel alan adı + white-label","Webhook + 365 günlük analitik"]}];
const faq=[
  ["Planımı daha sonra değiştirebilir miyim?","Evet. Kullanım hacminiz değiştiğinde hesabınızdan üst veya alt plana geçebilirsiniz; modelleriniz aynı çalışma alanında kalır."],
  ["AI kredileri nasıl çalışıyor?","Pro ve Business planlarındaki aylık üretim hakkı önce kullanılır. Aylık hak bittiğinde, varsa satın alınmış AI kredileriniz devreye girer."],
  ["Bir modeli kimlerin göreceğini seçebilir miyim?","Her model private, unlisted veya public olabilir. Pro planında şifreli ve süreli paylaşım bağlantıları da oluşturabilirsiniz."],
  ["Business planında özel alan adı var mı?","Evet. Business; organizasyon rolleri, özel alan adı, white-label görüntüleyici ve webhook özelliklerini içerir."]
];
export default function Pricing(){return <main><Header/><PageHero kicker="Şeffaf fiyatlandırma" title="Küçük başlayın. Sınırsız büyüyün." copy="İhtiyacınız değiştiğinde planınızı ve kapasitenizi çalışma alanınızı bozmadan büyütün."/><section className="pricing-grid">{plans.map((p,i)=><Reveal key={p.name} delay={i*90}><article className={p.popular?"popular":""}>{p.popular&&<em>EN POPÜLER</em>}<span>{p.name}</span><strong>{p.price}<small>/ay</small></strong><p>{p.copy}</p><button className={p.popular?"primary-btn wide":"secondary-btn wide"}>{p.name==="Free"?"Ücretsiz başla":"Planı seç"} →</button><div>{p.features.map(x=><p key={x}>✓ {x}</p>)}</div></article></Reveal>)}</section><section className="faq"><Reveal><span className="section-tag">SIK SORULANLAR</span><h2>Karar vermeden önce.</h2></Reveal>{faq.map(([q,a],i)=><Reveal key={q} delay={i*50}><details><summary>{q}<span>+</span></summary><p>{a}</p></details></Reveal>)}</section><Footer/></main>}
